/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.7.0.96.1 */
/* Module Version: 5.1 */
/* Sun Oct 08 21:45:03 2017 */

/* parameterized module instance */
uart_fifo __ (.Data( ), .Clock( ), .WrEn( ), .RdEn( ), .Reset( ), .Q( ), 
    .Empty( ), .Full( ));
