-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.7.0.96.1
-- Module  Version: 4.9
-- Mon Jan 22 13:19:37 2018

-- parameterized module component declaration
component MultiplierS16
    port (DataA: in  std_logic_vector(15 downto 0); 
        DataB: in  std_logic_vector(15 downto 0); 
        Result: out  std_logic_vector(31 downto 0));
end component;

-- parameterized module component instance
__ : MultiplierS16
    port map (DataA(15 downto 0)=>__, DataB(15 downto 0)=>__, Result(31 downto 0)=>__);
