-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.7.0.96.1
-- Module  Version: 3.5
-- Mon Jan 22 13:13:35 2018

-- parameterized module component declaration
component Subtractor
    port (DataA: in  std_logic_vector(15 downto 0); 
        DataB: in  std_logic_vector(15 downto 0); 
        Result: out  std_logic_vector(15 downto 0));
end component;

-- parameterized module component instance
__ : Subtractor
    port map (DataA(15 downto 0)=>__, DataB(15 downto 0)=>__, Result(15 downto 0)=>__);
