-- VHDL testbench template generated by SCUBA Diamond (64-bit) 3.7.0.96.1
library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.std_logic_unsigned.all;

use IEEE.math_real.all;

use IEEE.numeric_std.all;

entity tb is
end entity tb;


architecture test of tb is 

    component MultiplierS16
        port (DataA : in std_logic_vector(15 downto 0); 
        DataB : in std_logic_vector(15 downto 0); 
        Result : out std_logic_vector(31 downto 0)
    );
    end component;

    signal DataA : std_logic_vector(15 downto 0) := (others => '0');
    signal DataB : std_logic_vector(15 downto 0) := (others => '0');
    signal Result : std_logic_vector(31 downto 0);
begin
    u1 : MultiplierS16
        port map (DataA => DataA, DataB => DataB, Result => Result
        );

    process

    begin
      DataA <= (others => '0') ;
      for i in 0 to 200 loop
        wait for 10 ns;
        DataA <= DataA + '1' ;
      end loop;
      wait;
    end process;

    process

    begin
      DataB <= (others => '0') ;
      for i in 0 to 200 loop
        wait for 10 ns;
        DataB <= DataB + '1' ;
      end loop;
      wait;
    end process;

end architecture test;
