[ActiveSupport PAR]
; Global primary clocks
GLOBAL_PRIMARY_USED = 7;
; Global primary clock #0
GLOBAL_PRIMARY_0_SIGNALNAME = clk2;
GLOBAL_PRIMARY_0_DRIVERTYPE = PLL;
GLOBAL_PRIMARY_0_LOADNUM = 322;
; Global primary clock #1
GLOBAL_PRIMARY_1_SIGNALNAME = TEMP_CLK_c;
GLOBAL_PRIMARY_1_DRIVERTYPE = PLL;
GLOBAL_PRIMARY_1_LOADNUM = 390;
; Global primary clock #2
GLOBAL_PRIMARY_2_SIGNALNAME = clk3;
GLOBAL_PRIMARY_2_DRIVERTYPE = PLL;
GLOBAL_PRIMARY_2_LOADNUM = 0;
; Global primary clock #3
GLOBAL_PRIMARY_3_SIGNALNAME = jtaghub16_jtck;
GLOBAL_PRIMARY_3_DRIVERTYPE = JTAG;
GLOBAL_PRIMARY_3_LOADNUM = 269;
; Global primary clock #4
GLOBAL_PRIMARY_4_SIGNALNAME = reveal_ist_33_N;
GLOBAL_PRIMARY_4_DRIVERTYPE = SLICE;
GLOBAL_PRIMARY_4_LOADNUM = 76;
; Global primary clock #5
GLOBAL_PRIMARY_5_SIGNALNAME = clk_pid;
GLOBAL_PRIMARY_5_DRIVERTYPE = SLICE;
GLOBAL_PRIMARY_5_LOADNUM = 28;
; Global primary clock #6
GLOBAL_PRIMARY_6_SIGNALNAME = XY_CLK_c;
GLOBAL_PRIMARY_6_DRIVERTYPE = PIO;
GLOBAL_PRIMARY_6_LOADNUM = 18;
; # of global secondary clocks
GLOBAL_SECONDARY_USED = 4;
; Global secondary clock #0
GLOBAL_SECONDARY_0_SIGNALNAME = sys_rst_N;
GLOBAL_SECONDARY_0_DRIVERTYPE = SLICE;
GLOBAL_SECONDARY_0_LOADNUM = 53;
GLOBAL_SECONDARY_0_SIGTYPE = CE;
; Global secondary clock #1
GLOBAL_SECONDARY_1_SIGNALNAME = n25237;
GLOBAL_SECONDARY_1_DRIVERTYPE = SLICE;
GLOBAL_SECONDARY_1_LOADNUM = 43;
GLOBAL_SECONDARY_1_SIGTYPE = RST;
; Global secondary clock #2
GLOBAL_SECONDARY_2_SIGNALNAME = jtaghub16_jrstn;
GLOBAL_SECONDARY_2_DRIVERTYPE = JTAG;
GLOBAL_SECONDARY_2_LOADNUM = 256;
GLOBAL_SECONDARY_2_SIGTYPE = RST;
; Global secondary clock #3
GLOBAL_SECONDARY_3_SIGNALNAME = top_reveal_coretop_instance/core0/reset_rvl_n;
GLOBAL_SECONDARY_3_DRIVERTYPE = SLICE;
GLOBAL_SECONDARY_3_LOADNUM = 182;
GLOBAL_SECONDARY_3_SIGTYPE = RST;
; I/O Bank 0 Usage
BANK_0_USED = 12;
BANK_0_AVAIL = 20;
BANK_0_VCCIO = 3.3V;
BANK_0_VREF1 = NA;
BANK_0_VREF2 = NA;
; I/O Bank 1 Usage
BANK_1_USED = 3;
BANK_1_AVAIL = 6;
BANK_1_VCCIO = 3.3V;
BANK_1_VREF1 = NA;
BANK_1_VREF2 = NA;
; I/O Bank 2 Usage
BANK_2_USED = 6;
BANK_2_AVAIL = 18;
BANK_2_VCCIO = 3.3V;
BANK_2_VREF1 = NA;
BANK_2_VREF2 = NA;
; I/O Bank 3 Usage
BANK_3_USED = 4;
BANK_3_AVAIL = 4;
BANK_3_VCCIO = 3.3V;
BANK_3_VREF1 = NA;
BANK_3_VREF2 = NA;
; I/O Bank 4 Usage
BANK_4_USED = 1;
BANK_4_AVAIL = 8;
BANK_4_VCCIO = 3.3V;
BANK_4_VREF1 = NA;
BANK_4_VREF2 = NA;
; I/O Bank 5 Usage
BANK_5_USED = 3;
BANK_5_AVAIL = 18;
BANK_5_VCCIO = 3.3V;
BANK_5_VREF1 = NA;
BANK_5_VREF2 = NA;
; I/O Bank 6 Usage
BANK_6_USED = 5;
BANK_6_AVAIL = 8;
BANK_6_VCCIO = 3.3V;
BANK_6_VREF1 = NA;
BANK_6_VREF2 = NA;
; I/O Bank 7 Usage
BANK_7_USED = 3;
BANK_7_AVAIL = 18;
BANK_7_VCCIO = 3.3V;
BANK_7_VREF1 = NA;
BANK_7_VREF2 = NA;
