-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.7.0.96.1
-- Module  Version: 5.7
-- Sun Dec 10 18:45:40 2017

-- parameterized module component declaration
component pll_module
    port (CLK: in std_logic; CLKOP: out std_logic; CLKOS: out std_logic; 
        CLKOK: out std_logic; LOCK: out std_logic);
end component;

-- parameterized module component instance
__ : pll_module
    port map (CLK=>__, CLKOP=>__, CLKOS=>__, CLKOK=>__, LOCK=>__);
